function alertbtn(){
    var lop = document.getElementById("toalert").innerText ;
    alert(lop)
}
$(document).ready(function(){
    $('body').ready(function () {
        $('bag').append("<br/><br/><br/><br/><br/>");
    });
    $('body').ready(function () {
        $('#fadeout').fadeOut();
    });
    $('body').ready(function(){
        $('.to10').animate({
            width:'10px'
        });
        $('.to20').animate({
            width:'20px'
        });
        $('.to30').animate({
            width:'30px'
        });
        $('.to40').animate({
            width:'40px'
        });
        $('.to50').animate({
            width:'50px'
        });
        $('.to80').animate({
            width:'80px'
        });
        $('.to90').animate({
            width:'90px'
        });
        $('.to100').animate({
            width:'100px'
        });
        $('.to110').animate({
            width:'110px'
        });
        $('.to120').animate({
            width:'120px'
        });
        $('.to130').animate({
            width:'130px'
        });
        $('.to140').animate({
            width:'140px'
        });
        $('.to150').animate({
            width:'150px'
        });
        $('.to160').animate({
            width:'160px'
        });
        $('.to170').animate({
            width:'170px'
        });
        $('.to180').animate({
            width:'180px'
        });
        $('.to190').animate({
            width:'190px'
        });
        $('.to200').animate({
            width:'200px'
        });
        $('.to210').animate({
            width:'210px'
        });
        $('.to220').animate({
            width:'220px'
        });
        $('.to230').animate({
            width:'230px'
        });
        $('.to240').animate({
            width:'240px'
        });
        $('.to250').animate({
            width:'250px'
        });
        $('.to260').animate({
            width:'260px'
        });
        $('.to270').animate({
            width:'270px'
        });
        $('.to280').animate({
            width:'280px'
        });
        $('.to290').animate({
            width:'290px'
        });
        $('.to300').animate({
            width:'300px'
        });
        $('.to310').animate({
            width:'310px'
        });
        $('.to320').animate({
            width:'320px'
        });
        $('.to330').animate({
            width:'330px'
        });
        $('.to340').animate({
            width:'340px'
        });
        $('.to350').animate({
            width:'350px'
        });
        $('.to360').animate({
            width:'360px'
        });
        $('.to370').animate({
            width:'370px'
        });
        $('.to380').animate({
            width:'380px'
        });
        $('.to390').animate({
            width:'390px'
        });
        $('.to400').animate({
            width:'400px'
        });
        $('.to4000').animate({
            width:'400000px'
        }); 
        $('#to10').animate({
            width:'10px'
        });
        $('#to20').animate({
            width:'20px'
        });
        $('#to30').animate({
            width:'30px'
        });
        $('#to40').animate({
            width:'40px'
        });
        $('#to50').animate({
            width:'50px'
        });
        $('#to80').animate({
            width:'80px'
        });
        $('#to90').animate({
            width:'90px'
        });
        $('#to100').animate({
            width:'100px'
        });
        $('#to110').animate({
            width:'110px'
        });
        $('#to120').animate({
            width:'120px'
        });
        $('#to130').animate({
            width:'130px'
        });
        $('#to140').animate({
            width:'140px'
        });
        $('#to150').animate({
            width:'150px'
        });
        $('#to160').animate({
            width:'160px'
        });
        $('#to170').animate({
            width:'170px'
        });
        $('#to180').animate({
            width:'180px'
        });
        $('#to190').animate({
            width:'190px'
        });
        $('#to200').animate({
            width:'200px'
        });
        $('#to210').animate({
            width:'210px'
        });
        $('#to220').animate({
            width:'220px'
        });
        $('#to230').animate({
            width:'230px'
        });
        $('#to240').animate({
            width:'240px'
        });
        $('#to250').animate({
            width:'250px'
        });
        $('#to260').animate({
            width:'260px'
        });
        $('#to270').animate({
            width:'270px'
        });
        $('#to280').animate({
            width:'280px'
        });
        $('#to290').animate({
            width:'290px'
        });
        $('#to300').animate({
            width:'300px'
        });
        $('#to310').animate({
            width:'310px'
        });
        $('#to320').animate({
            width:'320px'
        });
        $('#to330').animate({
            width:'330px'
        });
        $('#to340').animate({
            width:'340px'
        });
        $('#to350').animate({
            width:'350px'
        });
        $('#to360').animate({
            width:'360px'
        });
        $('#to370').animate({
            width:'370px'
        });
        $('#to380').animate({
            width:'380px'
        });
        $('#to390').animate({
            width:'390px'
        });
        $('#to400').animate({
            width:'400px'
        });
        $('#to4000').animate({
            width:'400000px'
        });  
    });
});
